captainVersion: 4
caproverOneClickApp:
    variables:
        - label: HTTP Port
          description: This is the HTTP port to access appwrite
          defaultValue: '8000'
          id: $$cap_http_port
    instructions:
        start: |-
            A free, open source, and selfhostable Discord compatible chat, voice and video platform.
        end: |-
            Fosscord has been successfully deployed! Be sure to activate (or better yet, enforce) https access for $$cap_appname. 
    displayName: Fosscord
    isOfficial: false
    description: A free, open source, and selfhostable Discord compatible chat, voice and video platform.
    documentation: https://docs.fosscord.com/
########
services:
    $$cap_appname-appwrite:
        image: appwrite/appwrite:latest
        ports:
            - $$cap_http_port:80
            - $$cap_https_port:443
        volumes:
            - $$cap_appname-appwrite-uploads:/storage/uploads
            - $$cap_appname-appwrite-cache:/storage/cache
            - $$cap_appname-appwrite-config:/storage/config
            - $$cap_appname-appwrite-certificates:/storage/certificates
        depends_on:
            - $$cap_appname-mariadb
            - $$cap_appname-redis
            - $$cap_appname-clamav
            - $$cap_appname-influxdb
            - $$cap_appname-telegraf
        environment:
            _APP_ENV: production
            _APP_OPTIONS_FORCE_HTTPS: true
            _APP_OPENSSL_KEY_V1: $$cap_secret_key
            _APP_DOMAIN: http://$$cap_appname.$$cap_root_domain/
            _APP_DOMAIN_TARGET: http://$$cap_appname.$$cap_root_domain/
            _APP_CONSOLE_WHITELIST_EMAILS: $$cap_console_whitelist_emails
            _APP_REDIS_HOST: srv-captain--$$cap_appname-redis
